### ISSUE TITLE
Avaliação N1

### ISSUE THREAD

**Issue by scalabrinig** [ana-cecilia-ba/engenharia-software#1]
Parabéns ao grupo! Ideia interessante.

(10) Demanda ok.

(10) Requisitos ok.

- Esses requisitos são Funcionais:

IA para selecionar o piloto mais indicado para a entrega

- Esses requisitos são  Não Funcionais:

Desenvolvimento da interface gráfica do app

**Comment by Lucasdsf** [comment]
Garcias
